### ISSUE TITLE
Request: Support node versions 6.x

### ISSUE THREAD

**Issue by troy-lamerton** [mwiesmueller/node-poeditor#1]
The library is written using `async await` syntax and is incompatible with the current stable node version 6.11.x

All it would take is building the library with something like `babel lib/index.js --presets=env,node8`

I'd be happy to work on it if this is desired.

**Comment by mwiesmueller** [comment]
Hi Troy,

yes. I've written this library in node version greater than 8. 

All our modules are running in this versions. We love clean code :-)

When you like to work on it - It's no problem! You can send me a pull request.
